apiVersion: v1
kind: Service
metadata:
  name: buyerchat
  namespace: buyerchat
  labels:
    app.kubernetes.io/name: buyerchat
    app.kubernetes.io/component: web
    app.kubernetes.io/part-of: devops-showcase
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: buyerchat
    app.kubernetes.io/component: web
  ports:
    - name: http
      port: 3000
      targetPort: http
      protocol: TCP
