version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"

  - package-ecosystem: "helm"
    directory: "/helm/buyerchat"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"